{% set name = "amazon-q-developer-jupyterlab-ext" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-q-developer-jupyterlab-ext-{{ version }}.tar.gz
  sha256: 570fc513675d47a96094f1254b5eb02ecd089acc04a96092ba16a92ca3ef7556

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - jupyter_packaging >=0.10,<1.dev0,<2
    - jupyterlab >=4.0,<5.dev0
    - pip
  run:
    - python >=3.6
    - boto3
    - botocore
    - aiobotocore
    - jupyterlab >=4.0,<5.0

test:
  imports:
    - amazon_q_developer_jupyterlab_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/q/developer
  summary: Amazon Q Developer for JupyterLab
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - bhadrip
    - gogakoreli
    - kumarnzt
